[package]
authors = ["Kristoffer Solberg Rakstad <kristoffer.solberg@cognite.com>"]
autotests = false
categories = ["ai"]
description = "Behavior tree"
documentation = "https://docs.rs/bonsai-bt"
edition = "2021"
homepage = "https://github.com/sollimann/bonsai"
keywords = ["ai", "behavior", "tree", "robotics", "game"]
license = "MIT"
name = "bonsai-bt"
readme = "../README.md"
repository = "https://github.com/sollimann/bonsai.git"
rust-version = "1.60.0"
version = "0.4.9"

[lib]
name = "bonsai_bt"
path = "src/lib.rs"

[dependencies]
# BT
futures = "0.3.19"
petgraph = "0.6.2"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
# NodeEditor
glium = { version = "0.30.2", default-features = true }
imgui = { version = "0.8.2", features = ["tables-api"] }
imgui-glium-renderer = "0.8.2"
imgui-winit-support = "0.8.2"
imnodes = { git = "https://github.com/Sollimann/imnodes.rs", branch = "main" }
winit = "0.26.1"

[[test]]
name = "tests"
