# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "Action",
    "ActionArgs",
    "After",
    "AlwaysSucceed",
    "BT",
    "Behavior",
    "If",
    "Invert",
    "Race",
    "Select",
    "Sequence",
    "Status",
    "Wait",
    "WaitForever",
    "WhenAll",
    "WhenAny",
    "While",
    "WhileAll",
    "RUNNING",
]

@typing.final
class ActionArgs:
    r"""
    Action callback arguments.

    Constructed by the tick bridge and passed to the user's callback.
    The Rust `ActionArgs::event` field is intentionally not exposed —
    Python users only see `dt` and `action`.
    """
    @property
    def dt(self) -> builtins.float:
        r"""
        Remaining delta time in seconds.
        """
    @property
    def action(self) -> typing.Any:
        r"""
        The user-supplied action value (whatever was passed to `bt.Action(...)`).
        """
    def __new__(cls, dt: builtins.float, action: typing.Any) -> ActionArgs: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class BT:
    r"""
    A behavior-tree executor wrapping `bonsai_bt::BT<PyObject, PyObject>`.

    Construct from a tree and a blackboard, then drive with `.tick(dt, callback)`.
    The callback receives `(args, blackboard)` and must return `(Status, float)`.
    """
    def __new__(cls, behavior: Behavior, blackboard: typing.Any) -> BT: ...
    def tick(self, dt: builtins.float, callback: typing.Any) -> typing.Optional[tuple[Status, builtins.float]]: ...
    def blackboard(self) -> typing.Any: ...
    def reset_bt(self) -> None: ...
    def tick_count(self) -> builtins.int: ...
    def is_finished(self) -> builtins.bool: ...
    def graphviz(self) -> builtins.str: ...
    def with_telemetry(self, port: builtins.int, host: builtins.str = '127.0.0.1') -> BT: ...

@typing.final
class Behavior:
    r"""
    An opaque behavior-tree node.

    Construct via the factory functions (`Sequence`, `Action`, `Wait`, ...)
    at the module level. Subtrees are reusable - the same `Behavior`
    can appear as a child of multiple parents.
    """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Status(enum.Enum):
    r"""
    Behavior-tree node result.

    Mirrors `bonsai_bt::Status`. Comparable to `int`
    (`Status.Success == 0`, `Failure == 1`, `Running == 2`) and usable
    as a `dict` key or `set` member.
    """
    Success = ...
    Failure = ...
    Running = ...

    def __reduce__(self) -> tuple[typing.Any, tuple[typing.Any, builtins.str]]:
        r"""
        Pickle support: name the singleton by class + variant name, since
        PyO3 simple enums refuse construction by call (`Status(0)` raises).
        """

def Action(action: typing.Any) -> Behavior: ...

def After(children: typing.Sequence[Behavior]) -> Behavior: ...

def AlwaysSucceed(child: Behavior) -> Behavior: ...

def If(cond: Behavior, on_success: Behavior, on_failure: Behavior) -> Behavior: ...

def Invert(child: Behavior) -> Behavior: ...

def Race(children: typing.Sequence[Behavior]) -> Behavior: ...

def Select(children: typing.Sequence[Behavior], memory: builtins.bool = True) -> Behavior:
    r"""
    `Select(children, memory=True)`.

    `memory=True` (default) resumes the running child across ticks.
    `memory=False` restarts from the first child every tick.
    """

def Sequence(children: typing.Sequence[Behavior], memory: builtins.bool = True) -> Behavior:
    r"""
    `Sequence(children, memory=True)`.

    `memory=True` (default) resumes the running child across ticks.
    `memory=False` restarts from the first child every tick.
    """

def Wait(seconds: builtins.float) -> Behavior: ...

def WaitForever() -> Behavior: ...

def WhenAll(children: typing.Sequence[Behavior]) -> Behavior: ...

def WhenAny(children: typing.Sequence[Behavior]) -> Behavior: ...

def While(cond: Behavior, body: typing.Sequence[Behavior]) -> Behavior: ...

def WhileAll(cond: Behavior, body: typing.Sequence[Behavior]) -> Behavior: ...


RUNNING: typing.Final[tuple[Status, builtins.float]]
r"""Convenience constant: ``(Status.Running, 0.0)`` - return from a tick callback to keep the action running."""
