[package]
authors = ["Kristoffer Solberg Rakstad <kristoffer.solberg@cognite.com>"]
description = "Behavior tree examples"
edition = "2021"
name = "examples"
repository = "https://github.com/sollimann/bonsai.git"
rust-version = "1.60.0"
version = "0.1.0"

[dependencies]
bonsai = { path = "../bonsai" }

[[example]]
crate-type = ["bin"]
name = "3d"
path = "src/3d.rs"
