[package]
authors = ["Kristoffer Solberg Rakstad <kristoffer.solberg@cognite.com>"]
description = "Behavior tree examples"
edition = "2021"
name = "examples"
repository = "https://github.com/sollimann/bonsai.git"
rust-version = "1.60.0"
version = "0.1.0"

[dependencies]
bonsai = { path = "../bonsai" }
kiss3d = "0.34.0"
nalgebra = { version = "0.30", features = ["rand"] }
rand = "0.8"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"

[[example]]
crate-type = ["bin"]
name = "3d"
path = "src/3d.rs"

[[example]]
crate-type = ["bin"]
name = "boids"
path = "src/boids_swarm.rs"
