[package]
authors = ["Kristoffer Solberg Rakstad <kristoffer.solberg@cognite.com>"]
description = "Behavior tree examples"
edition = "2021"
name = "examples"
repository = "https://github.com/sollimann/bonsai.git"
rust-version = "1.60.0"
version = "0.1.0"

[dependencies]
find_folder = "0.3.0"
piston2d-sprite = "0.66.0"
piston_window = "0.123.0"

[[example]]
crate-type = ["bin"]
name = "sprite"
path = "src/sprite.rs"
